# Generated by Django 3.0.7 on 2020-08-18 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_house_host'),
        ('reviews', '0002_review_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='houses.House'),
        ),
    ]
