# Generated by Django 3.0.7 on 2020-06-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('cost', models.FloatField()),
                ('rooms', models.IntegerField()),
                ('garage', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('aircondition', models.BooleanField(default=False)),
            ],
        ),
    ]
