# Generated by Django 3.0.7 on 2020-09-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=150)),
                ('cost', models.FloatField()),
                ('rooms', models.IntegerField()),
                ('garage', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('aircondition', models.BooleanField(default=False)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=20)),
                ('image', models.ImageField(default='default.jpg', upload_to='images')),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('av_from', models.DateField()),
                ('av_to', models.DateField()),
                ('heat', models.BooleanField(default=False)),
                ('area', models.FloatField()),
                ('beds', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('transport_desc', models.CharField(max_length=150)),
                ('house_type', models.CharField(choices=[('entire_place', 'entire_place'), ('private_room', 'private_room'), ('shared_room', 'shared_room')], max_length=15)),
                ('people_num', models.IntegerField()),
                ('people_max', models.IntegerField()),
                ('rules', models.CharField(max_length=150)),
                ('plus_cost', models.IntegerField()),
            ],
        ),
    ]
