# Generated by Django 3.0.7 on 2020-06-19 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apartment',
            new_name='House',
        ),
    ]
