# Generated by Django 3.0.7 on 2020-08-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_house_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
    ]
