# Generated by Django 3.0.7 on 2020-09-09 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_auto_20200909_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='rooms',
        ),
    ]
